//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudStreams.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProblemDetails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProblemDetails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudStreams.Data.Properties.ProblemDetails", typeof(ProblemDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cluster resource cannot define a namespace.
        /// </summary>
        public static string ClusterResourceCannotDefineNamespace {
            get {
                return ResourceManager.GetString("ClusterResourceCannotDefineNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find clustered resource &apos;{group}/{version}/{plural}/{name}&apos;.
        /// </summary>
        public static string ClusterResourceNotFound {
            get {
                return ResourceManager.GetString("ClusterResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data schema &apos;{dataSchemaUri}&apos; does not exist or cannot be found.
        /// </summary>
        public static string DataSchemaNotFound {
            get {
                return ResourceManager.GetString("DataSchemaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validation policy for source &apos;{sourceUri}&apos; requires the cloud event&apos;s &apos;dataSchema&apos; attribute to be set.
        /// </summary>
        public static string MissingDataSchema {
            get {
                return ResourceManager.GetString("MissingDataSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find namespaced resource &apos;{group}/{version}/{plural}/{namespace}/{name}&apos;.
        /// </summary>
        public static string NamespacedResourceNotFound {
            get {
                return ResourceManager.GetString("NamespacedResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find namespace &apos;{namespace}&apos;.
        /// </summary>
        public static string NamespaceNotFound {
            get {
                return ResourceManager.GetString("NamespaceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected version: &apos;{expectedVersion}&apos;. Actual version: &apos;{actualVersion}&apos;.
        /// </summary>
        public static string OptimisticConcurrencyFailed {
            get {
                return ResourceManager.GetString("OptimisticConcurrencyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admission failed for operation &apos;{operation}&apos; on resource of type &apos;{group}/{version}/{plural}&apos;.
        /// </summary>
        public static string ResourceAdmissionFailed {
            get {
                return ResourceManager.GetString("ResourceAdmissionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find resource definition &apos;{group}/{version}/{plural}&apos;.
        /// </summary>
        public static string ResourceDefinitionNotFound {
            get {
                return ResourceManager.GetString("ResourceDefinitionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the storage version of the resource definition &apos;{group}.{plural}&apos;.
        /// </summary>
        public static string ResourceDefinitionStorageVersionNotFound {
            get {
                return ResourceManager.GetString("ResourceDefinitionStorageVersionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find version &apos;{version}&apos; of the resource definition &apos;{group}.{plural}&apos;.
        /// </summary>
        public static string ResourceDefinitionVersionNotFound {
            get {
                return ResourceManager.GetString("ResourceDefinitionVersionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert resource &apos;{group}/{version}/{plural}&apos; to version &apos;{version}&apos;.
        /// </summary>
        public static string ResourceVersionConversionFailed {
            get {
                return ResourceManager.GetString("ResourceVersionConversionFailed", resourceCulture);
            }
        }
    }
}
