apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gateways.cloud-streams.io
spec:
  scope: Cluster
  group: cloud-streams.io
  names:
    plural: gateways
    singular: gateway
    kind: Gateway
    shortNames:
    - gw
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                authorization:
                  type: object
                  properties:
                    decisionStrategy: 
                      type: string
                      enum:
                        - consensus
                        - minority
                        - unanimous
                      default: unanimous
                    rules:
                      type: array
                      items:
                        type: object
                        properties:
                          type:
                            type: string
                          attributeName:
                            type: string
                          attributeValue:
                            type: string
                          maxSize:
                            type: number
                          from:
                            type: string
                            format: date-time
                          to:
                            type: string
                            format: date-time
                        anyOf:
                          - properties:
                              type:
                                const: attribute
                            required:
                              - type
                              - attributeName
                          - properties:
                              type:
                                const: payload
                            required:
                              - type
                              - maxSize
                          - properties:
                              type:
                                const: timeOfDay
                            required:
                              - type
                              - from
                              - to
                          - properties:
                              type:
                                const: temporary
                            required:
                              - type
                              - from
                              - to
                validation:
                  type: object
                  properties:
                    skipValidation:
                      type: boolean
                    validationStrategy:
                      type: string
                      enum:
                        - none
                        - warn
                        - fail
                      default: fail
                    dataSchema:
                      type: object
                      properties:
                        required:
                          type: boolean
                          default: true
                        autoGenerate:
                          type: boolean
                sources:
                  type: array
                  items:
                    type: object
                    properties:
                      uri:
                        type: string
                        format: url
                      authorization:
                        type: object
                        properties:
                          decisionStrategy: 
                            type: string
                            enum:
                              - consensus
                              - minority
                              - unanimous
                            default: unanimous
                          rules:
                            type: array
                            items:
                              type: object
                              properties:
                                type:
                                  type: string
                                attributeName:
                                  type: string
                                attributeValue:
                                  type: string
                                maxSize:
                                  type: number
                                from:
                                  type: string
                                  format: date-time
                                to:
                                  type: string
                                  format: date-time
                              anyOf:
                                - properties:
                                    type:
                                      const: attribute
                                  required:
                                    - type
                                    - attributeName
                                - properties:
                                    type:
                                      const: payload
                                  required:
                                    - type
                                    - maxSize
                                - properties:
                                    type:
                                      const: timeOfDay
                                  required:
                                    - type
                                    - from
                                    - to
                                - properties:
                                    type:
                                      const: temporary
                                  required:
                                    - type
                                    - from
                                    - to
                      validation:
                       type: object
                       properties:
                         skipValidation:
                           type: boolean
                         validationStrategy:
                           type: string
                           enum:
                             - none
                             - warn
                             - fail
                           default: fail
                         dataSchema:
                           type: object
                           properties:
                             required:
                               type: boolean
                               default: true
                             autoGenerate:
                               type: boolean
                    required:
                      - uri
                events:
                  type: array
                  items:
                    type: object
                    properties:
                      source:
                        type: string
                      type:
                        type: string
                      metadata:
                        type: object
                        properties:
                          properties:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                strategy:
                                  type: string
                                  enum:
                                    - attribute
                                    - expression
                                attribute:
                                  type: object
                                  properties:
                                    name:
                                      type: string
                                    value:
                                      type: string
                                  required:
                                    - name
                                expression:
                                  type: string
                              anyOf:
                                - properties:
                                    strategy:
                                      const: attribute
                                  required:
                                    - name
                                    - attribute
                                - properties:
                                    strategy:
                                      const: expression
                                  required:
                                    - name
                                    - expression
                    required:
                      - source
                      - type
                service:
                  type: object
                  properties:
                    uri:
                      type: string
                      format: url
                    healthChecks:
                      type: object
                      properties:
                        request:
                          type: object
                          properties:
                            method:
                              type: string
                            path:
                              type: string
                            headers:
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
                            body:
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
                          required: [ method, path ]
                        interval:
                          type: string
                          pattern: '/^P([0-9]+(?:[,\.][0-9]+)?Y)?([0-9]+(?:[,\.][0-9]+)?M)?([0-9]+(?:[,\.][0-9]+)?D)?(?:T([0-9]+(?:[,\.][0-9]+)?H)?([0-9]+(?:[,\.][0-9]+)?M)?([0-9]+(?:[,\.][0-9]+)?S)?)?$/'
                      required: [ request ]
                  required:
                    - uri
            status:
              type: object
          required:
            - spec
      subresources:
        status: {}