apiVersion: cloud-streams.io/v1
kind: Network
metadata:
  name: network-1

---

apiVersion: cloud-streams.io/v1
kind: Gateway
metadata:
  name: gateway-1
spec:
  validation: #optional
    dataSchema:
      required: false
      autoGenerate: true
  sources: #optional
    - uri: https://some.domain/source
      authorization:
        rules:
          - type: attribute
            attributeName: subject
            attributeValue: '*'
  events:
    - source: '*'
      type: '*'
      metadata:
        properties:
          - name: '$correlationId'
            strategy: expression
            expression: |- 
              fetch('https://petstore.swagger.io/v2/pet/findByStatus?status=available')
                .then(response => response.json())
                .then(pets => pets[0].name);
          - name: '$causationId'
            strategy: expression
            expression: 'input.id'
            
---

apiVersion: cloud-streams.io/v1
kind: Broker
metadata:
  name: broker-1
spec:
  network: network-1
  dispatch:
    retryPolicy:
      statusCodes: [503]
      circuitBreaker:
        breakAfter: 5
        breakDuration: PT5S
      backoffDuration:
        type: exponential
        period: PT1S
        exponent: 2
  
---

apiVersion: cloud-streams.io/v1
kind: Subscription
metadata:
  name: webhook-site
  labels: #optional for now
    cloud-streams.io/network-id: network-1
spec:
  subscriber: #required
    uri: http://webhook-tester:18080/00000000-0000-0000-0000-000000000000
  #  rateLimit: 30
  #stream: #optional
  #  offset: 10 #optional: can be 0 for start, -1 for end, n for wherever in the stream
  #mutation: #optional
  #  type: expression
  #  expression: .data["foo"] = .data.foo | del(.data.foo)
