apiVersion: cloud-streams.io/v1
kind: Network
metadata:
  name: network-1

---

apiVersion: cloud-streams.io/v1
kind: Gateway
metadata:
  name: gateway-1
spec:
  validation: #optional
    dataSchema:
      required: false
      autoGenerate: true
  sources: #optional
    - uri: https://test.com/sys-admin
      authorization:
        rules:
          - type: attribute
            attributeName: subject
            attributeValue: '*'
            
---

apiVersion: cloud-streams.io/v1
kind: Broker
metadata:
  name: broker-1
spec:
  network: network-1
  
---

apiVersion: cloud-streams.io/v1
kind: Subscription
metadata:
  name: webhook-site
  labels: #optional for now
    cloud-streams.io/network-id: network-1
spec:
  subscriber: #required
    uri: https://webhook.site/171b5e49-7981-4232-afd6-ed18129cfe2f #required
    rateLimit: 30
  stream: #optional
    offset: 10 #optional: can be 0 for start, -1 for end, n for wherever in the stream
  mutation: #optional
    type: expression
    expression: .data["patientName"] = .data.name | del(.data.name)