apiVersion: cloud-streams.io/v1
kind: Network
metadata:
  name: network-1

---

apiVersion: cloud-streams.io/v1
kind: Gateway
metadata:
  name: gateway-1
spec:
  validation:
    dataSchema:
      required: false
      autoGenerate: true
  sources:
    - uri: https://mozart-dev.ccie.cisco.com/sys-admin
      authorization:
        rules:
          - type: attribute
            attributeName: subject
            attributeValue: '*'
            
---

apiVersion: cloud-streams.io/v1
kind: Broker
metadata:
  name: broker-1
spec:
  network: network-1
  
---

apiVersion: cloud-streams.io/v1
kind: Channel
metadata:
  name: channel-1
  labels:
    io.cloud-streams.network: network-1
spec:
  serviceAddress: https://webhook.site/04cec4fc-b213-428e-b7ba-12e4b7732b5f
  stream:
    offset: -1