apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: brokers.cloud-streams.io
spec:
  scope: Cluster
  group: cloud-streams.io
  names:
    plural: brokers
    singular: broker
    kind: Broker
    shortNames:
    - bkr
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                network:
                  type: string
                dispatch:
                  type: object
                  properties:
                    retryPolicy:
                      type: object
                      properties:
                        statusCodes:
                          type: array
                          items:
                            type: number
                        circuitBreaker:
                          type: object
                          properties:
                            breakAfter:
                              type: integer
                            breakDuration:
                              type: string
                          required:
                            - breakAfter
                            - breakDuration
                        backoffDuration:
                          type: object
                          properties:
                            type:
                              type: string
                              enum:
                                - constant
                                - incremental
                                - exponential
                            period:
                              type: string
                            exponent:
                              type: number
                          oneOf:
                            - properties:
                                type:
                                  enum: 
                                    - constant
                              required:
                                - type
                                - period
                            - properties:
                                type: 
                                  enum: 
                                    - incremental
                              required:
                                - type
                                - period
                            - properties:
                                type:
                                  enum: 
                                    - exponential
                              required:
                                - type
                                - period
                                - exponent 
                        maxAttempts:
                          type: integer
                      required:
                        - backoffDuration
                  required:
                    - retryPolicy
              required:
                - network
                - dispatch
            status:
              type: object
          required:
            - spec
      subresources:
        status: {}