apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networks.cloud-streams.io
spec:
  scope: Cluster
  group: cloud-streams.io
  names:
    plural: networks
    singular: network
    kind: Network
    shortNames:
    - net
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object