apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: subscriptions.cloud-streams.io
spec:
  scope: Cluster
  group: cloud-streams.io
  names:
    plural: subscriptions
    singular: subscription
    kind: Subscription
    shortNames:
    - sub
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                partition:
                  type: object
                  properties:
                    type:
                      type: string
                      enum:
                        - by-source
                        - by-type
                        - by-subject
                    id:
                      type: string
                  required:
                    - type
                    - id
                filter:
                  type: object
                  properties:
                    type:
                      type: string
                      enum:
                        - attributes
                        - expression
                    attributes:
                      type: object
                    expression:
                      type: string
                  oneOf:
                    - properties:
                        type:
                          enum: 
                            - attributes
                      required:
                        - type
                        - attributes
                    - properties:
                        type:
                          enum: 
                            - expression
                      required:
                        - type
                        - expression
                mutation:
                  type: object
                  properties:
                    type:
                      type: string
                      enum:
                        - expression
                        - webhook
                    expression:
                      type: string
                    webhook:
                      type: object
                      properties:
                        serviceUri:
                          type: string
                          format: url
                  oneOf:
                    - properties:
                        type:
                          enum: 
                            - expression
                      required:
                        - type
                        - expression
                    - properties:
                        type:
                          enum: 
                            - webhook
                      required:
                        - type
                        - webhook
                stream:
                  type: object
                  properties:
                    offset:
                      type: number
                subscriber:
                  type: object
                  properties:
                    uri:
                      type: string
                      format: url
                    rateLimit:
                      type: number
                    retryPolicy:
                      type: object
                      properties:
                        statusCodes:
                          type: array
                          items:
                            type: number
                        circuitBreaker:
                          type: object
                          properties:
                            breakAfter:
                              type: integer
                            breakDuration:
                              type: string
                          required:
                            - breakAfter
                            - breakDuration
                        backoffDuration:
                          type: object
                          properties:
                            type:
                              type: string
                              enum:
                                - constant
                                - incremental
                                - exponential
                            period:
                              type: string
                            exponent:
                              type: number
                          oneOf:
                            - properties:
                                type:
                                  enum: 
                                    - constant
                              required:
                                - type
                                - period
                            - properties:
                                type: 
                                  enum: 
                                    - incremental
                              required:
                                - type
                                - period
                            - properties:
                                type:
                                  enum: 
                                    - exponential
                              required:
                                - type
                                - period
                                - exponent 
                        maxAttempts:
                          type: integer
                      required:
                        - backoffDuration
                  required:
                    - uri
              required:
                - subscriber
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - inactive
                    - active
                    - disabled
                observedGeneration:
                  type: number
                stream:
                  type: object
                  properties:
                    ackedOffset:
                      type: number
                    fault:
                      type: object
                      properties:
                        type:
                          type: string
                          format: url
                        title:
                          type: string
                        status:
                          type: integer
                        detail:
                          type: string
                        instance:
                          type: string
                          format: url
                        errors:
                          type: array
                          items:
                            type: object
                      required:
                        - type
                        - title
                        - status
          required:
            - spec
      subresources:
        status: {}