apiVersion: v1
kind: Namespace
metadata:
  name: cloud-streams
  labels:
    name: cloud-streams

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: cloud-streams
  labels:
    app: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: ghcr.io/neuroglia-io/cloud-streams-api-server:latest
        ports:
        - containerPort: 80
        env:
        - name: CONNECTIONSTRINGS__REDIS
          value: ${REDIS_URI}
        - name: CONNECTIONSTRINGS__EVENTSTORE
          value: ${EVENTSTORE_URI}
        volumeMounts:
        - name: cloud-streams-plugins
          mountPath: /app/plugins/
      volumes:
      - name: cloud-streams-plugins
        hostPath:    
          path: /run/desktop/mnt/host/c/Users/User/.cloud-streams/plugins
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: cloud-streams
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: ghcr.io/neuroglia-io/cloud-streams-gateway:latest
        ports:
        - containerPort: 80
        env:
        - name: CONNECTIONSTRINGS__REDIS
          value: ${REDIS_URI}
        - name: CONNECTIONSTRINGS__EVENTSTORE
          value: ${EVENTSTORE_URI}
        - name: CLOUDSTREAMS_GATEWAY_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: cloud-streams-plugins
          mountPath: /app/plugins/
      volumes:
      - name: cloud-streams-plugins
        hostPath:    
          path: /run/desktop/mnt/host/c/Users/User/.cloud-streams/plugins
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  namespace: cloud-streams
  labels:
    app: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        image: ghcr.io/neuroglia-io/cloud-streams-broker:latest
        ports:
        - containerPort: 80
        env:
        - name: CONNECTIONSTRINGS__REDIS
          value: ${REDIS_URI}
        - name: CONNECTIONSTRINGS__EVENTSTORE
          value: ${EVENTSTORE_URI}
        - name: CLOUDSTREAMS_BROKER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: cloud-streams-plugins
          mountPath: /app/plugins/
      volumes:
      - name: cloud-streams-plugins
        hostPath:    
          path: /run/desktop/mnt/host/c/Users/User/.cloud-streams/plugins
---

apiVersion: v1
kind: Service
metadata:
  name: api-server
spec:
  selector:
    app: api-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  selector:
    app: broker
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80