version: '3.4'

services:

  eventstore:
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_RUN_PROJECTIONS=all
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
    ports:
      - "1113:1113"
      - "2113:2113"

  redis:
    image: redis:latest

  gateway:
    image: cloud-streams/gateway
    # image: ${DOCKER_REGISTRY-}gateway
    # build:
    #   context: ../../
    #   dockerfile: ./src/gateway/CloudStreams.Gateway.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 80
      CONNECTIONSTRINGS__REDIS: ${REDIS_URI}
      CONNECTIONSTRINGS__EVENTSTORE: ${EVENTSTORE_URI}
      CLOUDSTREAMS_GATEWAY_NAME: gateway-1
    ports:
      - 8080:80
    depends_on:
      - redis
      - eventstore

  broker:
    image: ${DOCKER_REGISTRY-}broker
    build:
      context: ../../
      dockerfile: ./src/broker/CloudStreams.Broker.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 80
      CONNECTIONSTRINGS__REDIS: ${REDIS_URI}
      CONNECTIONSTRINGS__EVENTSTORE: ${EVENTSTORE_URI}
      CLOUDSTREAMS_BROKER_NAME: broker-1
    depends_on:
      - redis
      - eventstore