version: '3.4'

services:

  eventstore:
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_RUN_PROJECTIONS=all
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-logs
        target: /var/log/eventstore

  redis:
    image: redis:latest

  api-server:
    image: ${DOCKER_REGISTRY-}api-server
    build:
      context: ../../
      dockerfile: ./src/core/CloudStreams.Core.Api.Server/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTIONSTRINGS__REDIS: ${REDIS_URI}
      CONNECTIONSTRINGS__EVENTSTORE: ${EVENTSTORE_URI}
    volumes:
      - ./plugins:/app/bin/Debug/net7.0/plugins
    depends_on:
      - redis
      - eventstore

  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: ../../
      dockerfile: ./src/gateway/CloudStreams.Gateway.Api.Server/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTIONSTRINGS__REDIS: ${REDIS_URI}
      CONNECTIONSTRINGS__EVENTSTORE: ${EVENTSTORE_URI}
      CLOUDSTREAMS_GATEWAY_NAME: gateway-1
    volumes:
      - ./plugins:/app/bin/Debug/net7.0/plugins
    depends_on:
      - redis
      - eventstore

volumes:
  eventstore-data:
  eventstore-logs:  