apiVersion: cloud-streams.io/v1
kind: Subscription
metadata:
  name: all
spec:
  subscriber:
    uri: https://events.k.ccie.cisco.com/events/pub
  stream:
    offset: -1
  retryPolicy:
    statusCodes: [ 503 ]
    circuitBreaker:
      breakAfter: 3
  breakDuration: PT5S
